public class TestOutter {
    public void outterMethod(){
        system.debug('This is outter class');
    }
    public class ChildClass1{
        public void child1Method(){
        	system.debug('This is child1 class');
    }
    }
    public class ChildClass2{
        public void child2Method(){
        	system.debug('This is child2 class');
    }
    }
    public class ChildClass3{
         public void child3Method(){
        	system.debug('This is child3 class');
    }
    }
}