import { createElement } from 'lwc';
import WireApex from 'c/wireApex';
import getAccountList from '@salesforce/apex/AccountController.getAccountList';

jest.mock('@salesforce/apex/AccountController.getAccountList', () =>{
    const { createApexTestWireAdapter } = require('@salesforce/sfdx-lwc-jest');
    return { default: createApexTestWireAdapter(jest.fn()), 
    };
},
    {virtual: true}
);

const mockGetAccountList = require('./data/getAccountList.json');

describe('c-wire-apex', () => {

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-wire-apex', {
            is: WireApex
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');

        //emit data from @wire
        getAccountList.emit(mockGetAccountList);

        return Promise.resolve().then(() => {

            const accountElement = element.shadowRoot.querySelectorAll('p');
            expect(accountElement.length).toBe(mockGetAccountList.length);
            expect(accountElement[0].textContent).toBe(mockGetAccountList[0].Name);
        }); 
    });
});